# Written largely by DeepSeek. We shall see…
name: Deploy mdbook to GitHub Pages

on:
  push:
    branches: [main]  # Change this to your source branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup mdbook and plugins
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.34'  # Match your required version
        plugins: mdbook-rss

    - name: Build mdbook with RSS
      run: mdbook build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # personal_token: ${{ secrets.DEPLOY_TOKEN }}
        # external_repository: FlamingosProject/flamingos-blog.github.io
        publish_branch: main  # Or 'gh-pages' depending on your settings
        publish_dir: ./book
        keep_files: false
